### ISSUE TITLE
🐛 Can't build assembleRelease - Hermes

### ISSUE THREAD

**Issue by guimiranda-dev** [cuvent/react-native-vision-camera#1222]
### What were you trying to do?

I can build app with assembleDebug, but when I build using assembleRelease it gives me the follow error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '../node_modules/hermes-engine/osx-bin/hermes''
```

**My app/build.gradle:**

```
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    hermesCommand: "../node_modules/hermes-engine/%OS-BIN%/hermes",
]

apply from: "../../node_modules/react-native/react.gradle"
``` 

### What happened instead?

It gives me the error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '../node_modules/hermes-engine/osx-bin/hermes''
```

### Device

Android

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
