### ISSUE TITLE
🐛 In react-native-vision-camera the contours values are always showing as [Array]

### ISSUE THREAD

**Issue by DeepikaSharma5** [cuvent/react-native-vision-camera#1226]
### What were you trying to do?

I want to fet the score of contours

### Reproduceable Code

```tsx
const frameProcessor = useFrameProcessor((frame) => {
    'worklet';
    const values = scanFaces(frame);
    runOnJS(setValues)(values);
  }, []);
```

### What happened instead?

The values of contours is always showing as [Array]
![image](https://user-images.githubusercontent.com/64214744/188498215-cc2b08fa-8f6c-4d3b-8f2d-dbe54e3bd61d.png)

### Device

Android - Samsung Galaxy A03

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
