### ISSUE TITLE
🐛 Camera scale in samsung j7

### ISSUE THREAD

**Issue by yleley** [cuvent/react-native-vision-camera#1227]
### What were you trying to do?

![photo_6102781596131242636_y](https://user-images.githubusercontent.com/71702851/188546955-7cae9f36-71f3-4810-88a5-860f9b1bd83d.jpg)

### What happened instead?

![photo_6102781596131242636_y](https://user-images.githubusercontent.com/71702851/188547038-1ecfb75e-416e-432c-af5a-f7955d74dfde.jpg)

### Device

samsung j7

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hamfer** [comment]
Are you using custom rom ?

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
