### ISSUE TITLE
🐛  Error in build type resolution

### ISSUE THREAD

**Issue by Dallas62** [cuvent/react-native-vision-camera#1379]
### What were you trying to do?

I wanted to build release build.

### Reproduceable Code

Just a clean build with the library.

### What happened instead?

Crash in the resolution of library link, looking for a debug library in release build.

Probably related to
- https://github.com/mrousavy/react-native-vision-camera/issues/588
-  https://github.com/mrousavy/react-native-vision-camera/issues/388

### Relevant log output

Didn't reproduce error after full clean, but build type resolution still select debug on release build.

```graddle
def resolveBuildType() {
    def buildType = "debug"
    tasks.all({ task ->
        logger.warn("VisionCamera:  ========================>>>>>>> TASK NAME ${task.name}")
        if (task.name == "buildCMakeRelease") {
            buildType = "release"
        }
    })
    return buildType
}
```

Return debug in any case.

The right `task.name` might be: `buildCMakeRelWithDebInfo`

### Device

Android build

### VisionCamera Version

2.9.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
