### ISSUE TITLE
[android] White screen before camera on 🐛 

### ISSUE THREAD

**Issue by ChauVV** [cuvent/react-native-vision-camera#1403]
### What were you trying to do?

I get a white screen in 3s before camera on.
```
            {device != null && hasPermission && (
                <Camera
                  ref={cameraRef}
                  onInitialized={showPopupInstruction}
                  style={StyleSheet.absoluteFill}
                  device={device}
                  isActive
                  orientation="portrait"
                  focusable
                  enableDepthData
                  photo
                />
             )}
```

### What happened instead?

I get a white screen in 3s before camera on.

### Device

android real device

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by shakuniyamihir8400** [comment]
Having the same issue here, Any update please

**Comment by parth-koshta** [comment]
@ChauVV @shakuniyamihir8400 
Hey guys, I'm facing the same issue on some devices. Were you able to find a workaround for this?

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!

**Comment by mrousavy** [comment]
The white screen might be because your View is white. Add backgroundColor: black to your view
