### ISSUE TITLE
🐛 The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher

### ISSUE THREAD

**Issue by srymarz** [cuvent/react-native-vision-camera#1431]
### What were you trying to do?

I want build app using react-native-vision-camera: 2.15.2 for react-native 0.70.6

### What happened instead?

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-actions-shortcuts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10

### Device

Android

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by zzz08900** [comment]
Why do you think react-native-actions-shortcuts has anything to do with react-native-vision-camera?

**Comment by alois-beto** [comment]
I added this in `android/build.gradle`:

```diff
buildscript {
    ext {
          [...]
+        kotlinVersion = "1.6.20"
    }
    [...]
}
```

**Comment by srymarz** [comment]
Hello, 
I agree this may not be a problem with the react-native-vision-camera, although it appeared after adding it to the project. I modified my `android/build.gradle` with `kotlinVersion="1.6.20"` but the problem still exists. I will contact the developers of the packages that cause the error with this problem

**Comment by zzz08900** [comment]
> Hello, I agree this may not be a problem with the react-native-vision-camera, although it appeared after adding it to the project. I modified my `android/build.gradle` with `kotlinVersion="1.6.20"` but the problem still exists. I will contact the developers of the packages that cause the error with this problem

To me it looks like you are having kotlin version conflicts in your dependencies, which, in most cases, should be fixed by specifying kotlin version in top-level build.gradle as suggested by @alois-beto.

You may want to look into your deps and check if some of them are not honoring your buildscript configurations and ask the corrosponding devs to fix it. Last I checked, react-native-vision-camera does honor buildscript configurations.

Or you might want to run a clean-rebuild cycle and see if anything changes.

Or you might want to patch your deps a little bit, forcing all of them to use 1.6.20 and see if CI complains about anything.

**Comment by thestretivibity** [comment]
I had the same problem after I installed the latest version, and here's I solved it

go to ``build.gradle`` as @alois-beto pointed out
``` 
buildscript {
    ext {
          [...]
        kotlinVersion = "1.6.20"
    }
}
```

and then build the project 2 times!

**Comment by chernandezlt** [comment]
I had the same error but including kotlinVersion fixed the issue <3

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
