### ISSUE TITLE
Is it possible to smooth zoom when changing camera device on Android❓ 

### ISSUE THREAD

**Issue by Sewb21** [cuvent/react-native-vision-camera#1461]
### Question

Hi there,

I am trying to smooth zoom between ultra-wide-angle and wide-angle by changing the device based on the zoom level, currently it kind of works but has a black screen for a short time in between switching which camera is used. Like what happens on iOS devices naturally

Is there any way around this or is it a limitation of the underlying android camera package?

### VisionCamera Version

2.15.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

If your device is a multi-cam and does not smooth-zoom, then it's the Android OS' fault. nothing I can do there tbh
