### ISSUE TITLE
Camera.getAvailableCameraDevices() returns null on Android, physical device🐛 

### ISSUE THREAD

**Issue by stivenm16** [cuvent/react-native-vision-camera#1462]
### What were you trying to do?

I'm trying to access to all available Camera Devices but it returns null when I'm running my app on a physical device, however when  I run the code in the emulator it works fine and returns a full array with options. The phone is connected via usb. This unexpected behaviour still persist after build it

### Reproduceable Code

```tsx
const TestComponent = () => {
  const { navigate } = useNavigation();
 
  useEffect(() => {
    const requestPermissions = async () => {
      await Camera.requestCameraPermission();
    };
    requestPermissions();
  });


  const devices = useCameraDevices();
  const device = devices.back;

  // console.log(devices, "devices"); => it returns null on physical device

  if (device == null)
    return (
      <View>
        <Text> Device null</Text>
      </View>
    );

  return (
    <View style={{ flex: 1, backgroundColor: "red", padding: 10 }}>
      <Camera style={{ flex: 1 }} device={device} isActive={true} />
      <Text>It works</Text>
    </View>
  );
};
```

### What happened instead?

useCameraDevices() returns null when is called on a physical device

### Device

Silver Max lite 2

### VisionCamera Version

2.15.2 - 2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by EmiBenitez** [comment]
any news about this? I have the same problem.

**Comment by Ntouris3** [comment]
I'm facing the same issue

**Comment by chj-damon** [comment]
I tried in `Smartisan` which is another brand and also the devices are all undefined.

**Comment by SohaibKtb** [comment]
same for Tecno devices

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
