### ISSUE TITLE
Example app fails to start in Android Emulator🐛 

### ISSUE THREAD

**Issue by zonotope** [cuvent/react-native-vision-camera#1520]
### What were you trying to do?

I am having trouble integrating this library in another app and wanted to troubleshoot the issue by installing and running the example app

### Reproduceable Code

```tsx
Example app with no changes
```

### What happened instead?

When I try to start the example app with `npx react-native start` in one terminal window and `npx react-native run-android` in a different one, the app is built successfully, but the emulator screen flickers and the app does not start. 

### Relevant log output

```shell
https://gist.github.com/zonotope/919418a901c89d8efead79203cf40d35
```

### Device

Pixel 6 Pro API 31 (emulator running in Android Studio)

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
