### ISSUE TITLE
Invalid argument type ImageProxy when trying to use native module and passing the frame as argument🐛 

### ISSUE THREAD

**Issue by Waseem6409** [cuvent/react-native-vision-camera#1536]
### What were you trying to do?

I am trying to create something of my own, i want to get the frames in native java, i am passing the frame as argument to my native code, as i have checked out the the projects built on this project, the type of Frame is ImageProxy in java , i have done the necessary imports, but when i try to trigger the native function, i get error that the argument i passed to my native function is of invalid type

### Reproduceable Code

```tsx
// Java code
 @ReactMethod
    public void AIProcessor(ImageProxy frame) {
        Log.d("AIProcess", "Triggered");
}

// React Native Code
AIProcessorModule.AIProcessor(frame)
```

### What happened instead?

The app crashes and in android studio logcat i found out the error is coming as invalid argument

### Device

Android 12

### VisionCamera Version

latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

Note: In this version, I don't use CameraX anymore, so `ImageProxy` is not used anymore. Now it's just `Frame.image` :)

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
