### ISSUE TITLE
🐛  [Android] Prop Camera orientation='landscapeLeft' results in picture oriented landscape right

### ISSUE THREAD

**Issue by rkostrab** [cuvent/react-native-vision-camera#1561]
### What were you trying to do?

I want to take a picture in my app in these conditions: 
- app is portrait-only orientation in the manifest (`android:screenOrientation="portrait"`), 
- user should lean the device to left 90 degrees (horizontal position) and take a picture
- using Camera prop `orientation='landscapeLeft'` I am expecting picture oriented correctly as a horizontal picture

### Reproduceable Code

```tsx
...
          <Camera
            ref={camera}
            style={styles.container}
            device={device}
            photo
            torch={isTorch ? 'on' : 'off' }
            zoom={zoom}
            isActive={isScreenFocused && !pictureTaken}
            onInitialized={() => setCameraReady(true)}
            orientation='landscapeLeft'
            onError={onError}/>

...

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustPan"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
```

### What happened instead?

When I set `orientation='landscapeLeft'` and lean device to the left 90 degrees I get the resulting picture oriented upside down ("landscape right"). 

Note: I've tried to set screenOrientation in manifest to full and removed orientation from Camera properties and do the same and the resulting picture was oriented correctly.

### Device

Google Pixel 6 Pro

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.
