### ISSUE TITLE
🐛 Wrong orientation of Camera preview on iPadOS

### ISSUE THREAD

**Issue by simonschwitzky** [cuvent/react-native-vision-camera#1614]
### What were you trying to do?

Render the preview of the front facing camera.

### Reproduceable Code

```tsx
import { StyleSheet } from 'react-native';
import { Camera, useCameraDevices } from 'react-native-vision-camera';

export { CameraScreen };

function CameraScreen(): JSX.Element {
	const devices = useCameraDevices();
	const device = devices.front;

	if (!device) return <></>;

	return (
		<Camera
			style={StyleSheet.absoluteFill}
			device={device}
			isActive={true}
			photo
		/>
	);
}
```

### What happened instead?

When the device is in landscape orientation, preview orientation is off by 90deg on landscape-right and off by -90deg on landscape-left.

### Device

iPad Pro (12,9", 3rd Generation)

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by fede-moveshelf** [comment]
Same issue

**Comment by babyjay-work** [comment]
I am having the same issue on an iPhone 7 (iOS 14.1) and an iPhone 12 (iOS 16.5) using react-native-vision-camera@2.15.4.  I did not have this issue on Expo SDK 45 and camera version 2.14.1.

When I have some free time, I may try to start at SDK 45 and upgrade one SDK at a time (and build new dev clients) to see when vision camera starts to break.

**Comment by thebabyjay** [comment]
I am having the same issue on an iPhone 7 (iOS 14.1) and an iPhone 12 (iOS 16.5) using react-native-vision-camera@2.15.4. I did not have this issue on Expo SDK 45 and camera version 2.14.1.

When I have some free time, I may try to start at SDK 45 and upgrade one SDK at a time (and build new dev clients) to see when vision camera starts to break.

**Comment by trashcoder** [comment]
same here with my iPhone 12.

**Comment by pdavid0** [comment]
Same issue here.
```
iPad mini 6th gen 
iOS 16.5.1


"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "^0.71.12",
"react-native-vision-camera": "^2.15.4",
"expo": "^48.0.19",
```

**Comment by HemangiVekaria** [comment]
I am having same issue. Any solution?

**Comment by eisodev** [comment]
Same issue here. iPhone 13 Pro, debugging on physical device. Front and back camera is the same.

On "react-native-vision-camera": "^2.15.6" because we can't upgrade our react native version yet.

I tried using:

```
import { useDeviceOrientation } from "@react-native-community/hooks";

const orientation = useDeviceOrientation();

orientation={orientation === 'portrait' ? 'portrait' : 'landscapeRight'}
```

But the orientation prop has no effect at all. I made sure the orientation for the hook updates correctly, which it does. I also tried forcing this prop to any of the values it can have, but still does nothing.

Instead of rotating 90 degrees, the camera rotates 180. Making the top go to side of the screen in landscape mode and not to the top.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

JFYI; Orientation is quite compelx but if I have neough sponsors I'll work on it. Camera sensors are always 90deg

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.
