### ISSUE TITLE
🐛Vision Camera Android example App keeps crashing after installation

### ISSUE THREAD

**Issue by FlyWong** [cuvent/react-native-vision-camera#1631]
### What were you trying to do?

I am trying test out Vision Camera. I cloned the project from Git into VS code, installed dependencies thru yarn and tried to run the example with 'yarn android'.

![WhatsApp Image 2023-06-22 at 18 33 39](https://github.com/mrousavy/react-native-vision-camera/assets/10432466/e01111a6-e5a8-4d68-b285-57326a9befa3)

The installed example App was installed on my Android phone but it kept crashing.

No error was flagged. May I know what should we check to get the example up and running?

![NoErrRunAndroid](https://github.com/mrousavy/react-native-vision-camera/assets/10432466/8e1d9faa-220e-49f7-9453-0966cba9a533)

I am running on a win 10 machine and Samsung A53 

### Reproduceable Code

```tsx
The original code from Git. No changes were made.
```

### What happened instead?

The Android example App should run

### Device

Samsung A53

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Can you run `adb logcat` and see what logs you get?

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
