### ISSUE TITLE
🐛 Trying to get face detector to work but frame processing is unavailable and are not enabled

### ISSUE THREAD

**Issue by Salvasgdo** [cuvent/react-native-vision-camera#1650]
### What were you trying to do?

I want to get face detecting to work

### Reproduceable Code

```tsx
useEffect(() => {
 console.log(faces, Date.now());
 }, [faces]);
 
   const frameProcessor = useFrameProcessor((frame) => {
     'worklet';
     const scannedFaces = scanFaces(frame);
     runOnJS(setFaces)(scannedFaces);
   }, []);
 
   useEffect(() => {
     getPermission()
   }, [])
 
   if (device == null) return <View />
  return (
    <View style={{ flex: 1 }}>
      <Camera
      ref={camera}
      style={styles.camera}
      device={device}
      isActive={true}
      orientation='portrait'
      photo={true}
      frameProcessorFps={5}
      frameProcessor={frameProcessor}
    />
       <Svg style={StyleSheet.absoluteFill}>
        <Defs>
          <Mask id="mask">
            <Rect x="0" y="0" width="100%" height="100%" fill="white" />
            <Ellipse
              cx="50%"
              cy="50%"
              rx="130"
              ry="180"
              fill="black"
            />
          </Mask>
        </Defs>
        <Rect x="0" y="0" width="100%" height="100%" fill="rgba(0, 0, 0, 0.6)" mask="url(#mask)" />
      </Svg>

      <View
        style={{
          alignItems: 'center',
          position: 'absolute',
          bottom: 0,
          width: '100%',
          paddingBottom: 70,
        }}
      >
       <TouchableOpacity style={styles.loginButton} onPress={takePicture} >
            <Text style={styles.buttonText}>Tomar</Text>
          </TouchableOpacity>
      </View>
    </View>
  )
};
```

### What happened instead?

> bug frame-processor/unavailable: Frame Processors are not enabled. See https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting, js engine: hermes

### Relevant log output

```shell
frame-processor/unavailable: Frame Processors are not enabled. See https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting, js engine: hermes
```

### Device

Physical Android Redmi 

### VisionCamera Version

^2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by dhruvv-lanatus** [comment]
I am also facing this issue. Have you found any solution?

**Comment by xgenem** [comment]
What a bummer...

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
