### ISSUE TITLE
❓Abandoned version 2.x.x support while waiting for version 3

### ISSUE THREAD

**Issue by ronjunevaldoz** [cuvent/react-native-vision-camera#1657]
### Question

Upon discovering this library, I was drawn to it as it was suggested as the preferred alternative to react-native-camera, a framework I trust the most. However, my experience with the latest release, version 2.15.4, has been disappointing due to numerous unresolved issues, some of which have been submitted by the community but remain unaddressed. Many users find this situation frustrating, as the recommended library lacks proper maintenance. I consistently encounter responses from the developer, suggesting that these issues will only be addressed if we pay for support or provide our own solutions. In my opinion, this approach is inappropriate for an open-source community project, and it saddens me to see it being recommended despite these challenges.

Why is the 2.x.x abandoned?

### What I tried

manually patching up fixes `yarn patch-package`

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by latobibor** [comment]
The situation is this:
- you use `react-native` most likely because you don't have the resources to hire full-time Android/iOS devs, so you are quite less likely to just ship your own camera package
- previous camera packages are discontinued/abandoned especially with RN versions `0.70+`
- lot of things are only compatible with the new react versions and a lot of things are incompatible with the new RN versions
- there are not many maintained alternatives and they have huge issues; for example `react-native-camera-kit` after some signs of abandonment it has some traction recently, but I can't bet on it yet
- then you arrive to this package, but it is maintained by an enthusiastic hobbyist in his _spare time_

In this case we see the shortcomings of the open source experiment. He has every right to decline our requests, and we have no deterministic way to get what we want. I'm also frustrated with the situation, but it is not the author of the package I should be furious with but with Meta abandoning camera part of their `react-native` ecosystem.

You can't have hobbyists in the supply chain of a professional SDK. Speaking of professional SDKs probably you can get this functionality through expo, but their `expo-camera` does not work in the `emulator` (because _f-you that's why_ if you ask me) - that's why I wait a bit more for a miracle.

**Comment by ronjunevaldoz** [comment]
@latobibor, it seems you're assuming I rely on this library. In reality, I'm just inquiring to make an informed decision about whether I should develop my own library. I generally prefer using existing solutions and not reinventing the wheel, but this particular scenario might require me to do so (ohh miracle).

**Comment by mrousavy** [comment]
> I consistently encounter responses from the developer, suggesting that these issues will only be addressed if we pay for support or provide our own solutions. In my opinion, this approach is inappropriate for an open-source community project, and it saddens me to see it being recommended despite these challenges.

lol, huh? Do I owe you something my g? My time is valuable and I currently spend it on creating VisionCamera V3, a completely new version of this package which will fix pretty much 90% of the issues it currently has while also setting a new standard for cameras on mobile because of the Skia Frame Processors feature.

If you expect me to spend hours debugging issues **you** are experiencing and fixing them so **you** can release your product faster so **you** make money, then you're wrong, sorry.
The software is provided as is, and **it works great in my production apps and a lot of other apps out there** - sometimes they pay me to help them with some stuff.

Often the errors are because of some version incompatibilities, I'm addressing those in V3 as well.
