### ISSUE TITLE
"app:checkDebugDuplicateClasses" error for Android.

### ISSUE THREAD

**Issue by Ankit-Micron** [cuvent/react-native-vision-camera#1671]
### What were you trying to do?

Hey

I am also trying to use a vision-camera-code-scanner. The app works fine for iOS, but I get the "app:checkDebugDuplicateClasses" error for Android.

Here are my versions:
"react-native": "0.68.1",
"react-native-reanimated": "^2.8.0",
"react-native-vision-camera": "^2.14.1",
"vision-camera-code-scanner": "^0.2.0"

### What happened instead?

<img width="1343" alt="Screenshot 2023-07-28 at 10 29 25" src="https://github.com/mrousavy/react-native-vision-camera/assets/82659116/e609b5b6-4b2d-426b-be48-1fda3836ca1b">

### Relevant log output

```shell
It is working fine for iOS. This issue comes only for android devices
```

### Device

Android devices

### VisionCamera Version

0.68.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mohshafie** [comment]
Same happening for me after upgrading jdk to 17 and gradle to 7.6
<img width="2555" alt="Screenshot 2023-08-01 at 3 34 49 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/85107255/7ad6074c-94f3-4281-8bdf-74a3468fb578">

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
