### ISSUE TITLE
🐛 Recorded video appears green with only audio

### ISSUE THREAD

**Issue by PrernaBudhraja** [cuvent/react-native-vision-camera#1675]
### What were you trying to do?

I want to record a video on Vivo v20 device.

### Reproduceable Code

```tsx
<ReanimatedCamera
            key={`${cameraKey}`}
            style={{
              aspectRatio: 4 / 3,
              flex: 1,
            }}
            device={device}
            isActive={isFocused}
            ref={camera}
            photo
            video={isVideo}
            audio
            torch={torchStatus()}
            enableZoomGesture
            animatedProps={animatedProps}
            format={{
              ...device?.formats[0],
              photoWidth: 1920,
              photoHeight: 1440,
              videoWidth: 640,
              videoHeight: 480,
            }}
            onError={(error) => {
              console.log('RnReportLibrary -> Camera -> VisionCamera component Error:', error);
            }}
          />

camera.current.startRecording({
          flash,
          fileType: 'mp4',
          onRecordingFinished: async (video) => {
            setIsRecording(false);
            _saveVideo(`file://${video.path}`);
          },
          onRecordingError: (error) => {
            console.error(error);
          },
        });
```

### What happened instead?

Video recorded appears green when viewed. Only audio is present.
<img width="363" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/124996843/bf6cabb8-24a9-4673-8816-22b1e9656eea">

### Device

Vivo V20

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
