### ISSUE TITLE
[Android] camera session is bound and idle on unmount 🐛 

### ISSUE THREAD

**Issue by Skizu** [cuvent/react-native-vision-camera#1685]
### What were you trying to do?

An app that has multiple camera device controllers will be blocked from using camera devices or creating camera sessions due to unclosed and unbound camera sessions.

### What happened instead?

Camera session unable to be created due to limit reached.

### Relevant log output

```shell
2023-08-08 14:43:46.488 15004-15023 CameraManagerGlobal     {app_id}        I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client {app_id} API Level 2
...
2023-08-08 14:44:54.638 15004-15973 {TAG}      {app_id}        E  Camera2Session: Error: Camera device could not be opened because there are too many other open camera devices.
...
```

### Device

Samsung S10-S22, Samsung XCover Pro V3-6, Pixel 3a-6

### VisionCamera Version

2.15.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
