### ISSUE TITLE
Do not use "mrousavy" as  temp file name.

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#1861]
### What feature or enhancement are you suggesting?
Simplify library migration from v2 to v3 and also improve user usability.

[`File.createTempFile("mrousavy", extension, context.cacheDir)`](https://github.com/mrousavy/react-native-vision-camera/blob/42d9948e8aec338fa53c47dc26b7aa7714b35b25/package/android/src/main/java/com/mrousavy/camera/CameraView%2BTakePhoto.kt#L119C3-L119C63)
[`outputFile = File.createTempFile("mrousavy", fileType.toExtension(), context.cacheDir)`](https://github.com/mrousavy/react-native-vision-camera/blob/42d9948e8aec338fa53c47dc26b7aa7714b35b25/package/android/src/main/java/com/mrousavy/camera/core/RecordingSession.kt#L48C5-L48C91)

Is there any reason to use own nickname in temporary file?

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

I guess it is better to use "tmp_" instead of "mrousavy".
`File.createTempFile("tmp_", extension, dir)`

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
> Is there any reason to use own nickname in temporary file?

Yea - I spent more than 2,000 hours on VisionCamera and thousands of people use it without saying thanks or sponsoring the project, even though I saved them at least 50,000€ (up to 300,000€ if they use all the features in the library) since they no longer have to build a full Camera from scratch. There is a shit ton of research, debugging, testing, and advanced knowledge put into this.
Using mrousavy here just helps me see if an app is using VisionCamera internally, which is exciting to see.

It's only a temp file, you're supposed to remove it later anyways. (Either store to Gallery or upload to server).
