### ISSUE TITLE
❓ Is Frame Processors are currently read-only?

### ISSUE THREAD

**Issue by MrSolimanKing** [cuvent/react-native-vision-camera#1904]
### Question

I was wondering if possible to implement the camera filters like Snapchat or face beauty filters on ` react-native-vision-camera` I am aware it is possible to apply and show it in the camera view, but my question is about applying the filters on the video and then saving ita as file (with the filters not only raw video), is ` react-native-vision-camera` has hardware capture pipeline read and write to the file or it will require third bart libraries like `ffmpeg`.

### VisionCamera Version

3.2.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Yea, I have this feature working perfectly on my end with an amazingly nice to use API including filters, shaders, etc, but I decided to not integrate that into VisionCamera because it just overcomplicated the codebase a lot and users that don't use these features (probably >90% of users) will suffer under that because of some build issues or larger npm size. See [this section in the docs](https://www.react-native-vision-camera.com/docs/guides/skia-frame-processors)
