### ISSUE TITLE
✨ Text Recognition

### ISSUE THREAD

**Issue by sebasptsch** [cuvent/react-native-vision-camera#1939]
### What feature or enhancement are you suggesting?

I think that It would be awesome if `react-native-vision-camera` supported text recognition in the same way that it supports barcodes/qr codes. Using the iOS native APIs or MLKit on Android.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Currently trying to re-work `vision-camera-ocr` to work with the new version of `react-native-vision-camera`.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey!

No sorry this is not something I want to integrate into VisionCamera. QR/Barcode already was a tough decision since VisionCamera's goal is to stay as lean as possible, allowing the user to extend the API however he wants with powerful APIs that allow you to run fully native Frame Processor Plugins.

If I add QR-Code, people will want text recognition. If I add text recognition, people will want face detection. If I add face detection, people will want object detection.

Just write a frame processor plugin, it ain't that hard 😅

**Comment by sebasptsch** [comment]
Yeah no worries @mrousavy . I can definately see the logic behind this decision and am eager to explore how frame processors work anyway.

Thanks for all your work!

**Comment by mrousavy** [comment]
awesome thanks!

**Comment by eobruno** [comment]
I tried to use react-native-vision-camera-v3-text-recognition but does not work on IOS, just android.
