### ISSUE TITLE
Vision camera is zoomed than default camera

### ISSUE THREAD

**Issue by saikiruba-mj** [cuvent/react-native-vision-camera#1981]
### Question

Hi all

I am using react-native-vision-camera 2.15.4 with react 18.2.0 and react-native 0.72.1. While comparing the default camera view and vision-camera view it slightly zoomed than the default camera. Also, this scenario is only replicated on Android 13 and above versions.

### What I tried

Below are sample code 

```
const camera = useRef(null);
const devices = useCameraDevices('wide-angle-camera');
const device = isFrontCamera ? devices.front : devices.back;

 <Camera
    style={StyleSheet.absoluteFill}
    ref={camera}
    device={device}
    isActive={true}
    photo={true}
    preset="medium"
    enableZoomGesture={true}
    torch={device?.hasTorch && isFlashOn ? 'on' : 'off'}
    zoom={0}
/>
```

Also, I have tried to upgrade the react-native-vision-camera package version to the latest 3.3.1 but facing a build on Android on the frame processors section.

Does anyone have an idea how to resolve the zoom issue on the existing version(2.15.4)?

Please refer to the screenshot below for more details

Thank you! 
![Untitled (1)](https://github.com/mrousavy/react-native-vision-camera/assets/74354881/4455cb72-fe99-4775-bc72-6abdedfe4729)

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by zzz08900** [comment]
Try this first
`resizeMode={'contain'}`

**Comment by saikiruba-mj** [comment]
Hi @zzz08900 

Thanks for your comment. I have tried resizeMode={'contain'} in the Camera component and it doesn't work and unable to find the resizeMode prop in version 2.15.4. 

Also, I guess the mentioned props are related to VisionCamera V3.

Do you have another idea to resolve this scenario?

**Comment by zzz08900** [comment]
> Hi @zzz08900
> 
> Thanks for your comment. I have tried resizeMode={'contain'} in the Camera component and it doesn't work and unable to find the resizeMode prop in version 2.15.4.
> 
> Also, I guess the mentioned props are related to VisionCamera V3.
> 
> Do you have another idea to resolve this scenario?

Another approach would require your code to calculate width/height ratio based on pixel size info gathered from the hardware and assign appropriate width/height to the camera view, aka, implement `resizeMode={'contain'}` using js.
I guess that's what needs to be done in v2.

**Comment by blancham** [comment]
Indeed, `resizeMode` prop was added in [v3.1.0](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v3.1.0) so you will not be able to use it 😕

Nonetheless, your problem does not seem to be the `zoom` level but the style you are applying to the `Camera` a.k.a `StyleSheet.absoluteFill`. In fact, until v3.1.0, the `Camera` is only displayed using a `cover` resizeMode (but you need a `contain` resizeMode to make this work. As @zzz08900 pointed it out, you'll need to use JS for this!

What you need to do :

- Specify your own format, find a `16:9` format that suits you the best (on the screenshot to the right, it's using a 16:9 format). Be careful, the documentation is now for v3. In your version, you'll need to get it from `device.formats`
- Once you have your desired `16:9` format, forward it to the `Camera` using the `format` prop
- Now comes the JS part, I will not be able to build you an example app but the idea is simple, the `Camera` view needs to have a style that says  "take all the `width` you can" (e.g. `width: "100%"` or `flexGrow: 1` based on your parent style) **AND** that your view will fit using an aspect ratio of `16 / 9` (`aspectRatio: 9 / 16`). _It's reversed because we want it in portrait._

I hope it'll work for you 😁

**Comment by mrousavy** [comment]
Thanks for your help @blancham & @zzz08900! I really appreciate some maintenance help from the community here ❤️🙏  

Are you on the community discord? What's your discord handles? I'll give you moderator/contributor roles there

**Comment by mrousavy** [comment]
@saikiruba-mj; yea upgrade to V3. Then you can either use resizeMode, or the new format API to select the same format as the stock Camera app.

In V2, idk either zoom it out as @blancham said or select a different format. I believe they use 4:3 formats by default
