### ISSUE TITLE
takeSnapshot💭 

### ISSUE THREAD

**Issue by facucalle92** [cuvent/react-native-vision-camera#2487]
### Question

Has the function of taking a snapshot been removed?
Why?

### What I tried

I tried to takeSnapshot like version 2.13.3 but the takeSnapshot function is not defined.
Why did yo erase that function?
I was using it to take low quality pictures, because the takePhoto function cannot set quality option like snapshot.
<img width="665" alt="Captura de pantalla 2024-01-31 a la(s) 13 56 44" src="https://github.com/mrousavy/react-native-vision-camera/assets/54385211/ddcb2779-f0ec-4067-b5f9-b7303cb1a19c">

### VisionCamera Version

3.8.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - yes, `takeSnapshot` is now gone since I rewrote the entire codebase and I just didn't re-implement it in V3 yet because no one needed it yet.

`takePhoto` takes photos in the resolution defined by it's format, so take a look at [choosing a Format](https://react-native-vision-camera.com/docs/guides/formats).

I think we _could_ add `takeSnapshot` again, but this would require around 40 hours of effort. You can contact me through my agency if you want to pay for this feature, otherwise I'm closing this for now :)
