### ISSUE TITLE
🐛 Issue with QR Code Scanning: Delayed Scanning Failure

### ISSUE THREAD

**Issue by Abdulhaque4241** [cuvent/react-native-vision-camera#2710]
### What's happening?

When attempting to scan a QR code directly facing the device camera, it scans quickly. However, if the camera is opened for a few seconds (2 to 3 seconds) before attempting to scan a QR code, the scanning process does not occur (no error is shown). To provide more detail, scanning works when the device camera is facing a QR code directly, but if the camera is left open for 2 to 3 seconds before attempting to scan a QR code, the scanning process fails. Why does this issue occur and how can it be resolved?

### Reproduceable Code

```tsx
const codeScanner = useCodeScanner({
    codeTypes: ['qr', 'ean-13'],
    onCodeScanned: async codes => {
      if (codes[0].value) {
        console.log('codes[0].value', codes[0].value);
      }
    },
});

{device && (
 <Camera
  ref={camera}
  style={{flex: 1}}
  codeScanner={codeScanner}
  device={device}
  isActive={true}
 />
)}
```

### Relevant log output

```shell
//no logs
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "maxExposure": 20,
  "supportsLowLightBoost": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 10,
  "minExposure": -20,
  "name": "0 (BACK) androidx.camera.camera2",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Samsung galaxy note 10

### VisionCamera Version

^4.0.0-beta.8

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey - I think this issue has been fixed in [VisionCamera 4.0.0](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0). 🥳 

Please try V4 and let me know if you still experience this issue;
- if not, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support the development of VisionCamera and thank me for my time spent on fixing bugs and building new features.
- if you still see this issue, please comment and we can re-open this. But please update your native logs with the native (Xcode/Android Studio) logs from running VisionCamera V4 so I can investigate this.
