### ISSUE TITLE
✨ Capture progress callbacks

### ISSUE THREAD

**Issue by jkaufman** [cuvent/react-native-vision-camera#3145]
### What feature or enhancement are you suggesting?

RNVC could expose callbacks for capture progress. This would enable a refined UX with coaching for users and a more responsive shutter button. The capture lifecycle and callbacks available on Android and iOS differ, so the only expectation is to have a way of identifying when capture starts (exposure begins), capture ends, and file writing ends.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

None.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Such callbacks will likely be too slow for RN events. RN events are asynchronous, they come from a different thread than the JS thread. So it will have delays.

VisionCamera already has `onShutter`, which is the only event you will likely need, I don't see a reason for any other intermediate events to be added, but please correct me if you think otherwise.
