### ISSUE TITLE
❓ Is there anyway to limit the camera recognition area

### ISSUE THREAD

**Issue by fe-noob** [cuvent/react-native-vision-camera#820]
### Question

Hi,

 I use react-native-vision-camera and vision-camera-code-scanner to scan qrcode.

But i can't find any options to limit the scan area, i don't want the whole area can recognize the code. 

There are some solutions for react-native-camera, most of them are  to modify iOS/Android code.

Look forward to your reply.

### What I tried

No response

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi!

You can shoot a PR to vision-camera-code-scanner to implement this feature.

**Comment by xulihang** [comment]
I use react-native-svg to draw the scan region and pass the region info to [vision-camera-dynamsoft-barcode-reader](https://github.com/xulihang/vision-camera-dynamsoft-barcode-reader/). Since the plugin supports limiting the area, I just pass the left, right, top, bottom info to it. (Check out the [blog](https://www.dynamsoft.com/codepool/react-native-qr-code-scanner-vision-camera.html) for details)

If the barcode reader doesn't support this, we may need to crop the image by ourselves.
