### ISSUE TITLE
Video callback lacking data❓ 

### ISSUE THREAD

**Issue by nica0012** [cuvent/react-native-vision-camera#948]
### Question

Hi, I am in the middle of migrating over from react-native-camera.

I am noticing that the video callback only provides the uri and type. Am i missing something?

I feel like this is not enough.

What if I want to get the height and width of the video, the size, ratio, etc...? RNCamera had much more of a result for the video.

Besides this, I am a fan of the library. Good work!

Cheers.

### What I tried

Look through docs, no luck.

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey!
Agreed, there can be more information there, similar to how a Photo has Exif data.
Only thing that matters here is performance, we don't want to cause any slowdowns just by getting data that is not needed by some users.

I'm closing this because you posted this as a question, please re-post this as a feature request.
