### ISSUE TITLE
🐛 Frame is sideways on android portrait orientation

### ISSUE THREAD

**Issue by jslok** [cuvent/react-native-vision-camera#960]
### What were you trying to do?

When using frame processor on android in portrait mode, the frame is rotated to the left. When rotated to landscape mode, the frame is the correct orientation. 

Orientation prop from #715 does not seem to have an effect here. This prop is not mentioned in the docs either.

I can always rotate it in my custom frame processor but it seems like it should be presented in portrait if the device is in portrait.

### What happened instead?

Frame should be the correct orientation in portrait.

### Device

galaxy s20

### VisionCamera Version

2.12.0 and 2.13.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by jslok** [comment]
Here's screenshots of what I mean. In each screenshot, the top is the camera live view and the bottom is the frame from frameprocessor.
![277245470_569968350731650_9191431795062350398_n](https://user-images.githubusercontent.com/22921326/161240527-25d44112-b1e6-4c85-aff0-d1c205e7313b.jpg)
![277314834_683356056440161_5265776470730607191_n](https://user-images.githubusercontent.com/22921326/161240554-8ea9830d-6ddd-4582-bb68-a4fb278b99eb.jpg)

**Comment by mrousavy** [comment]
Hey, thanks for the detailed issue and explanation with screenshots.

You're right, this is actually a big issue, the Frame should be oriented correctly - does the `Frame.orientation` value change at all or is it `portrait` in every case?

**Comment by mrousavy** [comment]
I think this is the native orientation of the frame, since Camera sensors are in landscape orientation by default. If I would actually rotate the frame (moving each pixel to it's rotated value), this would be really really slow because I have to do that every frame.

If the `Frame.orientation` value is correct, there's not much more to do since this is what is expected by all frame processing libraries like MLKit Vision (they all have a `orientation` flag that tells them how to interpret the frame)

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.
