### ISSUE TITLE
🐛 React native vison camera build stopped at 92%

### ISSUE THREAD

**Issue by badalchangba** [cuvent/react-native-vision-camera#999]
### What were you trying to do?

![WhatsApp Image 2022-04-13 at 6 38 06 PM](https://user-images.githubusercontent.com/86218682/163762038-58d8fa42-99be-4a32-b8a6-bd5a12c7c7d5.jpeg)
![WhatsApp Image 2022-04-13 at 6 49 42 PM](https://user-images.githubusercontent.com/86218682/163762046-ff201da8-8d51-4ef1-88b2-e6f683244ca3.jpeg)
![WhatsApp Image 2022-04-13 at 4 35 25 PM](https://user-images.githubusercontent.com/86218682/163762052-32187e3f-cef7-43f1-a967-6328f1ae8bff.jpeg)

### Reproduceable Code

```tsx
I have java 11 and running the react app with proper react-native vison configuration and running the app.

npm run android
```
but my build configuration stops at 92%. What might be the cause for this issue?
```


### What happened instead?

My build configuration get stuck at 92%

### Relevant log output

_No response_

### Device

Honor 9N

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by syedtehrimabbas** [comment]
Having the same issue on MacBook M1 Pro with device android 12.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/26393867/163840250-f32b9d51-dc50-4f8b-a241-122fb3447dfb.png">

**Comment by mrousavy** [comment]
Looks like you don't have the NDK installed and it is trying to install it, which just takes a very long time apparently.

This is mentioned [in the Troubleshooting guide](https://mrousavy.com/react-native-vision-camera/docs/guides/troubleshooting#android).

Install the NDK separately, clean cache maybe restart your PC and then try again

**Comment by EKOzkan** [comment]
If anybody still experiences this same issue that is caused by ndk setup after the doing the steps in the [Troubleshooting guide](https://mrousavy.com/react-native-vision-camera/docs/guides/troubleshooting/#android),  try installing the **exact ndk version** that you see in the terminal text via android studio. 

Here is a little guide for this:


Check the version first

![image](https://user-images.githubusercontent.com/44098870/182043133-da28c9d1-1860-43d9-b43e-ca644cc03e5b.png)


Go to Android Studio - Sdk Manager, then get to the Sdk tools tab. Then toggle the "Show Package Details" option. 

![image](https://user-images.githubusercontent.com/44098870/182043225-51202959-765e-4e5c-b79c-a215c0aed4e5.png)


And download the **exact version** that you see in your terminal.

![image](https://user-images.githubusercontent.com/44098870/182043329-f7704273-e6ac-4aea-8a52-319057e74e72.png)

And you should be good to go. If you encounter any errors based on ndk, you can try this too:

Go to your projects android folder, create a file called "local.properties", and inside that file enter your sdk location like this:

`sdk.dir=C:\\Users\\!!!USERNAMEHERE!!!\\AppData\\Local\\Android\\Sdk`
